### ISSUE TITLE
uncaught (in promise) timeout

### ISSUE THREAD

**Issue by immunity20** [dozoisch/react-google-recaptcha#103]
Hello I have 2 screens.
In first screen a simple recaptcha displayed (sitekey onchange function)
which allow to click button to second screen.
On second screen after some time console prints uncaught (in promise) timeout

**Comment by hartzis** [comment]
can you make a codesandbox.io example? using the [template codsandbox.io/react-google-recaptcha](https://codesandbox.io/s/1y4zzjq37l)?

and/or do you have some screenshots? code examples anything to help us debug with you?

**Comment by RubtsovAV** [comment]
Some additional: This error appears after unmount the recaptcha component. It does not matter whether the user interacted with the CAPTCHA.

**Comment by hartzis** [comment]
@immunity20 Thank you for the example, i was able to get it to trigger once, but after @RubtsovAV comment about the unmount i can get it to error all the time.

I'll try to find some time next week to dig into it a bit more. thinking it has something to do with cleaning it up properly and or the `reset` call.

@immunity20 is it "breaking" your app?

**Comment by MiroslavPetrik** [comment]
I'm having the same issue. Could be the reset function as mentioned above.

**Comment by subvertallchris** [comment]
There's an open issue with Google Recaptcha, https://github.com/google/recaptcha/issues/269. Might be nice if anyone else wanted to comment there so they'll give it some attention.

**Comment by schnogz** [comment]
I had the `uncaught (in promise) timeout` error and after some debugging, I realized in my `onChange` callback, I was calling `this` in an incorrectly bound context which was silently failing.  I fixed that issue and the uncaught in promise error went away.

Moral of the story, make sure there are no script errors happening in component lifecycles or callbacks that may in turn cause Google's code to error.

**Comment by fluffy-samurai** [comment]
@hartzis @immunity20 Is the component unmounting as mentioned here? https://github.com/google/recaptcha/issues/269#issuecomment-434752317

If not, this may be an error on this side.

**Comment by fluffy-samurai** [comment]
Otherwise, @TomPradat may have more information.

**Comment by TomPradat** [comment]
Well i just looked at the source code from this repository to make this statement

**Comment by hartzis** [comment]
Thanks to @RubtsovAV and @dozoisch we think this should be fixed with #120 and [v1.0.5](https://github.com/dozoisch/react-google-recaptcha/releases/tag/v1.0.5).

I updated the [react-google-recaptcha/codesandbox.io](https://codesandbox.io/s/1y4zzjq37l) to use `v1.0.5` and i can't get the timeout to happen anymore.

**Comment by subvertallchris** [comment]
I'm still getting the timeout after upgrading. Any troubleshooting tips?

**Comment by RubtsovAV** [comment]
@subvertallchris Is your root element the body tag?

**Comment by omidnikrah** [comment]
Is there a helpful solution? I'm using `v1.0.5` but I have the same issue.

**Comment by RubtsovAV** [comment]
Yeah, now for some reason it has appeared again :(

**Comment by sgwanlee** [comment]
Using 1.10.0, I got the same error reported in Sentry.
After resetting synchronously,  I've got no error anymore.

```
const recaptchaRef = useRef();

const handleSubmit = () => {
   try {
       await login();
       await recaptchaRef.current.reset();
       history.push('/profile');
    } catch {
      ...
   }
}

<form onSubmit={handleSubmit}>
       <ReCAPTCHA
            style={{ display: "inline-block" }}
            ref={recaptchaRef}
            sitekey={recaptchaKey}
            size={size}
            onChange={onChange}
          />
</form>
```

**Comment by JoshuaKGoldberg** [comment]
Yup, this is still an issue 😞. I had a form that, upon submission:

1. Executed reCAPTCHA
2. Removed the reCaptcha element from the DOM
3. Submitted the form

This issue went away when the code was changed to always include the element in the DOM, even after submission.
Removing a bunch of details:

```diff
const Form = () => {
  const [submitted, setSubmitted] = useState(false);
  const reCaptchaElement = <ReCAPTCHA /* ... */ />; 

  return (
    <>
      {submitted
        ? <div>Thanks for submitting!</div>
        : (
          <form onSubmit={() => {
            /* ... */
            reCAPTCHA.execute();
            setSubmitted(true);
            /* ... */
          }}>
            <input /* ... */ />
-           {reCaptchaElement}
          </form>
        )
      }
+     {reCaptchaElement}
    </>
  );    
}
```

**Comment by sgwanlee** [comment]
Is `reset` necessary on umount? I just removed `this.reset()` in `componentWillUnmount`

**Comment by armspkt** [comment]
Seems like this error was fixed in v2.1.0

**Comment by hartzis** [comment]
@sgwanlee I think you're on to something. Going to clean this up in a PR and see what it looks like. Great suggestion.

**Comment by hartzis** [comment]
@sgwanlee Additionally investigated why it was put there orginally.

We have/had issues with `Error: ReCAPTCHA has already been rendered in this element` but i'm starting to suspect this may not be an issue any longer 🤔 
- https://github.com/dozoisch/react-google-recaptcha/issues/55
- PR with fix at the time - https://github.com/dozoisch/react-google-recaptcha/pull/73

**Comment by aytacg26** [comment]
> ## Never mind, it doesn't work.
> Using 1.10.0, I got the same error reported in Sentry. After resetting synchronously, I've got no error anymore.
> 
> ```
> const recaptchaRef = useRef();
> 
> const handleSubmit = () => {
>    try {
>        await login();
>        await recaptchaRef.current.reset();
>        history.push('/profile');
>     } catch {
>       ...
>    }
> }
> 
> <form onSubmit={handleSubmit}>
>        <ReCAPTCHA
>             style={{ display: "inline-block" }}
>             ref={recaptchaRef}
>             sitekey={recaptchaKey}
>             size={size}
>             onChange={onChange}
>           />
> </form>
> ```

If you do not want to generate a new reCAPTCHA challenge, I believe, when you submit the form, you shouldn't reset the recaptcha. The error occurs from reset process, because reseting it forces the Recaptcha widget to reload unnecessarily and at the same time most probably after submit process, you are unmounting it and hence it cannot find the widgetId and creates timeout error.

**Comment by NvIGA** [comment]
Since there's no proper way to handle it, just add it in the CSS root level to suppress Webpack fullscreen overlay errors.

Or configure webpack to ignore fullscreen overlay


```
#webpack-dev-server-client-overlay-div {
  display: none !important;
}

#webpack-dev-server-client-overlay {
  display: none !important;
}

```


```
module.exports = {
  devServer: function (configFunction) {
    return function (proxy, allowedHost) {
      // Create the default config by calling configFunction with the proxy/allowedHost parameters
      const config = configFunction(proxy, allowedHost);

      config.client = {
        overlay: false,
      };

      return config;
    };
  },
};
```
